/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    ArticleMetadata: typeof import('./src/components/article-metadata.vue')['default']
    BannerLightroomPresets: typeof import('./src/components/banner-lightroom-presets.vue')['default']
    BlogCard: typeof import('./src/components/blog-card.vue')['default']
    CompanyTimeline: typeof import('./src/components/company-timeline.vue')['default']
    Cookies: typeof import('./src/components/cookies.vue')['default']
    DeferredContent: typeof import('primevue/deferredcontent')['default']
    DynamicContent: typeof import('./src/components/dynamic-content.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FurtherLegal: typeof import('./src/components/further-legal.vue')['default']
    FurtherReading: typeof import('./src/components/further-reading.vue')['default']
    FurtherServices: typeof import('./src/components/further-services.vue')['default']
    GalleryItem: typeof import('./src/components/gallery-item.vue')['default']
    HeroImage: typeof import('./src/components/hero-image.vue')['default']
    HeroVideo: typeof import('./src/components/hero-video.vue')['default']
    Image: typeof import('./src/components/image.vue')['default']
    LatestArticle: typeof import('./src/components/latest-article.vue')['default']
    Map: typeof import('./src/components/map.vue')['default']
    NavBar: typeof import('./src/components/nav-bar.vue')['default']
    ParsedImage: typeof import('./src/components/ParsedImage.vue')['default']
    RequestAProposal: typeof import('./src/components/request-a-proposal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    SkeletonArticle: typeof import('./src/components/skeleton-article.vue')['default']
    SkeletonGalleryItem: typeof import('./src/components/skeleton-gallery-item.vue')['default']
    SkeletonServices: typeof import('./src/components/skeleton-services.vue')['default']
    SkeletonSwiper: typeof import('./src/components/skeleton-swiper.vue')['default']
    SwiperClients: typeof import('./src/components/swiper-clients.vue')['default']
    SwiperColourGrade: typeof import('./src/components/swiper-colour-grade.vue')['default']
    SwiperColourGrading: typeof import('./src/components/swiper-colour-grading.vue')['default']
    SwiperEmployees: typeof import('./src/components/swiper-employees.vue')['default']
    SwiperReels: typeof import('./src/components/swiper-reels.vue')['default']
    SwiperReviews: typeof import('./src/components/swiper-reviews.vue')['default']
    SwiperServices: typeof import('./src/components/swiper-services.vue')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
    Timeline: typeof import('primevue/timeline')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
