/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    BannerLightroomPresets: typeof import('./src/components/banner-lightroom-presets.vue')['default']
    BlogCard: typeof import('./src/components/blog-card.vue')['default']
    Controls: typeof import('./src/components/controls.vue')['default']
    Cookie: typeof import('./src/components/cookie.vue')['default']
    Cookies: typeof import('./src/components/cookies.vue')['default']
    Flags: typeof import('./src/components/flags.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GalleryItem: typeof import('./src/components/gallery-item.vue')['default']
    HeroVideo: typeof import('./src/components/hero-video.vue')['default']
    NavBar: typeof import('./src/components/nav-bar.vue')['default']
    Privacyoptions: typeof import('./src/components/privacyoptions.vue')['default']
    RequestAProposal: typeof import('./src/components/request-a-proposal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    SwiperClients: typeof import('./src/components/swiper-clients.vue')['default']
    SwiperEmployees: typeof import('./src/components/swiper-employees.vue')['default']
    SwiperReels: typeof import('./src/components/swiper-reels.vue')['default']
    SwiperReviews: typeof import('./src/components/swiper-reviews.vue')['default']
    Timeline: typeof import('primevue/timeline')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
