openapi: 3.0.0
info:
  title: Slavic Media API
  description: MongoDB ExpressJS NodeJS REST API
  version: 1.0.0
servers:
  - url: http://localhost:4000/
    description: Local backend
  - url: http://localhost:5173/
    description: Local frontend
  - url: https://dev.slavic.media
    description: Deployed frontend
  - url: https://api.slavic.media
    description: Deployed backend
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: auth-token
  schemas:
    Employee:
      type: object
      properties:
        _id:
          type: string
        index:
          type: number
        name:
          type: string
        department:
          type: string
        origin:
          type: string
        email:
          type: string
        birthday:
          type: string
        linkedin:
          type: string
        github:
          type: string
    Article:
      type: object
      properties:
        _id:
          type: string
        author:
          type: object
          properties:
            thumbnail:
              type: string
            name:
              type: string
            url:
              type: string
        metadata:
          type: object
          properties:
            date:
              type: string
              format: date-time
            formatedDate:
              type: string
            icon:
              type: string
            keywords:
              type: array
              items:
                type: string
            linkedin:
              type: string
            thumbnail:
              type: string
            length:
              type: number
        content:
          type: array
          items:
            type: string
        title:
          type: string
        videos:
          type: array
          items:
            $ref: "#/components/schemas/Video"
    Review:
      type: object
      properties:
        _id:
          type: number
        img:
          type: string
        name:
          type: string
        role:
          type: string
        profileLink:
          type: string
        rating:
          type: number
        fullReview:
          type: string
        message:
          type: string
    Video:
      type: object
      properties:
        _id:
          type: string
        index:
          type: number
        flag:
          type: string
        title:
          type: string
        url:
          type: string
        year:
          type: string
        client:
          type: string
    VideoGallery:
      type: object
      properties:
        _id:
          type: string
        index:
          type: number
        desc:
          type: string
        title:
          type: string
        videos:
          type: array
          items:
            $ref: "#/components/schemas/Video"
    Legal:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        modified:
          type: string
        content:
          type: array
          items:
            type: string
    Event:
      type: object
      properties:
        _id:
          type: number
        date:
          type: string
        event:
          type: string
        icon:
          type: string
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        date:
          type: string
    Img:
      type: object
      properties:
        _id:
          type: string
        alt:
          type: string
        title:
          type: string
        flag:
          type: string
    ImgGallery:
      type: object
      properties:
        _id:
          type: string
        index:
          type: number
        desc:
          type: string
        title:
          type: string
        columns:
          type: array
          items:
            type: array
            items:
              $ref: "#/components/schemas/Img"
paths:
  /user/register:
    post:
      summary: Register a new User
      description: Register a new User in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  _ID:
                    type: string
  /user/login:
    post:
      summary: Login a User
      description: Login a User to get a JWT token (auth-token)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: string
  /blog/articles:
    get:
      summary: Fetches all articles
      description: Retrieves a list of articles as JSON objects
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: A list of JSON objects in an array
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
    post:
      summary: Create a new article
      description: Creates a new article and sends it to the server for storage.
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Article"
      responses:
        201:
          description: Article created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
    delete:
      summary: Delete all articles
      description: Deletes all articles from the database
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: All articles deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /blog/articles/{id}:
    get:
      summary: Retrieve a specific article
      description: Retrieves a specific article based on its ID
      parameters:
        - in: path
          name: id
          required: true
          description: Article ID
          schema:
            type: string
      responses:
        200:
          description: An article in the format of a JSON object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
    put:
      summary: Update a specific article
      description: Updates a specific article based on its ID
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: Article ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Article"
      responses:
        200:
          description: Successfully updated!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
    delete:
      summary: Delete a specific article
      description: Deletes a specific article based on its ID
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: Article ID
          schema:
            type: string
      responses:
        200:
          description: Successfully deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
  /employees:
    get:
      summary: Fetches all employees
      description: Retrieves a list of employees as JSON objects
      responses:
        200:
          description: A list of JSON objects in an array
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
    post:
      summary: Create a new employee
      description: Creates a new employee and sends it to the server for storage.
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
      responses:
        201:
          description: Employee created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
    delete:
      summary: Delete all employees
      description: Deletes all employees from the database
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: All employees deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
/employees/{id}:
  get:
    summary: Retrieve a specific employee
    description: Retrieves a specific employee based on its ID
    parameters:
      - in: path
        name: id
        required: true
        description: Employee ID
        schema:
          type: string
    responses:
      200:
        description: An employee in the format of a JSON object
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
  put:
    summary: Update a specific employee
    description: Updates a specific employee based on its ID
    security:
      - ApiKeyAuth: []
    parameters:
      - in: path
        name: id
        required: true
        description: Employee ID
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Employee"
    responses:
      200:
        description: Successfully updated!
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
  delete:
    summary: Delete a specific employee
    description: Deletes a specific employee based on its ID
    security:
      - ApiKeyAuth: []
    parameters:
      - in: path
        name: id
        required: true
        description: Employee ID
        schema:
          type: string
    responses:
      200:
        description: Successfully deleted
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
/reviews:
  get:
    summary: Fetches all reviews
    description: Retrieves a list of reviews as JSON objects
    responses:
      200:
        description: A list of JSON objects in an array
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Review"
  post:
    summary: Create a new review
    description: Creates a new review and sends it to the server for storage.
  /event/{id}:
    put:
      summary: Update an event by id
      tags: [Event]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The event id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
      responses:
        200:
          description: The event was updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        404:
          description: The event was not found
    delete:
      summary: Delete an event by id
      tags: [Event]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The event id
      responses:
        200:
          description: The event was deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        404:
          description: The event was not found
  /employees:
    get:
      summary: Returns the list of all employees
      tags: [Employee]
      responses:
        200:
          description: The list of the employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
    post:
      summary: Create a new employee
      description: Creates a new employee and sends it to the server for storage.
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
      responses:
        201:
          description: Employee created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
    delete:
      summary: Delete all employees
      description: Deletes all employees from the database
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: All employees deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /employees/{id}:
    get:
      summary: Get the employee by id
      tags: [Employee]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The employee id
      responses:
        200:
          description: The employee description by id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        404:
          description: The employee was not found
    put:
      summary: Update an employee by id
      tags: [Employee]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The employee id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
      responses:
        200:
          description: The employee was updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        404:
          description: The employee was not found
    delete:
      summary: Delete an employee by id
      tags: [Employee]
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The employee id
      responses:
        200:
          description: The employee was deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        404:
          description: The employee was not found
  components:
    schemas:
      Review:
        type: object
        properties:
          id:
            type: number
          content:
            type: string
          rating:
            type: number
      VideoGallery:
        type: object
        properties:
          id:
            type: string
          title:
            type: string
          description:
            type: string
      Legal:
        type: object
        properties:
          id:
            type: string
          title:
            type: string
          content:
            type: string
      Img:
        type: object
        properties:
          id:
            type: string
          url:
            type: string
          description:
            type: string
      Event:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
          date:
            type: string
      Employee:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
          department:
            type: string
