// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/15/2025, 8:30:20 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/adamsochorec/Desktop/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/adamsochorec/Desktop/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/adamsochorec/Desktop/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/adamsochorec/Desktop/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/adamsochorec/Desktop/frontend/plugins/**/*.{js,ts,mjs}","/Users/adamsochorec/Desktop/frontend/composables/**/*.{js,ts,mjs}","/Users/adamsochorec/Desktop/frontend/utils/**/*.{js,ts,mjs}","/Users/adamsochorec/Desktop/frontend/pages/blog.vue","/Users/adamsochorec/Desktop/frontend/pages/test.vue","/Users/adamsochorec/Desktop/frontend/pages/about.vue","/Users/adamsochorec/Desktop/frontend/pages/index.vue","/Users/adamsochorec/Desktop/frontend/pages/legal.vue","/Users/adamsochorec/Desktop/frontend/pages/services/photo.vue","/Users/adamsochorec/Desktop/frontend/pages/services/video.vue","/Users/adamsochorec/Desktop/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/adamsochorec/Desktop/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/adamsochorec/Desktop/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;